CREATE SEQUENCE IF NOT EXISTS address_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 1;

CREATE TABLE ADDRESS (
    ID BIGINT PRIMARY KEY DEFAULT nextval('ADDRESS_SEQ'::regclass),
    STREET VARCHAR(255) NOT NULL,
    STREET_NUMBER INT NOT NULL,
    HOUSE_NUMBER INT NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    POSTAL_CODE VARCHAR(20) NOT NULL,
    IS_DEFAULT BOOL NOT NULL DEFAULT FALSE,
    BILLING_ADDRESS BOOL,
    SHIPPING_ADDRESS BOOL,
    USER_ID BIGINT
);


ALTER TABLE ADDRESS
ADD CONSTRAINT FK_USER
FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID);