server:
  port: 8080
spring:
  session:
    store-type:
      redis
  web:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*"
      exposed-headers: "*"
      allow-credentials: true
  redis:
    port: 6379
    host: localhost
  #  mail:
  #    host: ${HOST}
  #    port: ${PORT}
  #    username: ${USERNAME}
  #    password: ${PASSWORD}
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          starttls:
  #            enable: true
  application:
    name: security-service
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    user: admin
    password: password
    schemas: public
    locations: classpath:db
    clean-disabled: true
    baseline-on-migrate: true
    baseline-version: '0.0'
jwt:
  secret: ceve #${SECRET_KEY}
  salt: eeee #${SALT}

